# Generated by Django 2.2.12 on 2020-08-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('nationality', models.TextField(max_length=20)),
                ('phonenumber', models.TextField(max_length=10)),
                ('email_address', models.TextField(max_length=100)),
                ('personal_statement', models.TextField()),
                ('employment_history', models.TextField()),
                ('academic_achievements', models.TextField()),
                ('interests', models.TextField()),
                ('other', models.TextField()),
                ('references', models.TextField()),
            ],
        ),
    ]
